#5 Project: Smashing Magazine Teardown (HTML + CSS)
chubaquelo/Smashing-Mag-Teardown pull request #1
Opened 2020-09-01 20:56 UTC by chubaquelo

I made the project with mixed text and div placeholders, all in white and black color palette.
The changes I have made as follows:

- First HTML + CSS Layout sketch
- Added Linters
- Finished Headers Layout
- Moved CSS and IMG to folders
- Set the article's layout
- Added improvements to articles and header layout
- Added remaining sections: Community links, book offer
- Fixed layout and CSS errors
- Finished footer section
- Improved design, classes, and HTML code again.
- Added newsletter form and styled it
- Made more fixes and changed fontawesome icons to icons8 images
- I made final improvements on spacings and style
- Update README.md file

2020-09-01 22:52 UTC, kevcap requested changes
# [STATUS] CHANGES REQUIRED♻️

#### Hey @chubaquelo hello again! As always your project is looking amazing buddy, you're really good with details and design congrats! It breaks my heart not aprove it right away, and I mean it. But we just have to fix just TWO minor issues and you're good to go ! 💪
 
_Note_: That changes marked as [OPTIONAL] are not required to approve your project, but I strongly recommend that you guys go for that extra mile, to get more knowledge and have a better project to add at your portfolio.

### Me reading your code: 
<img src="https://media1.giphy.com/media/OwQn9LCHFcQ5G/giphy.gif">
 
 
## [REQUIRED CHANGES]
- [ ] Please remove all the **commented piece of codes** in your css. If you need to review a previous version of your code, use git history ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/no_inline_comments.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))  
:x: **commented piece of codes** /* `.nav { color: red;}` */  
:heavy_check_mark: **comments about code** /*Navigation */  

- [ ] Kindly remember to remove all the unnecessarily repeated CSS code. Keeping your code DRY is an excellent practice that will help you a lot and make your code more professional. (Check this link form better understanding [Good and Bad CSS Practices for Beginners](https://speckyboy.com/good-bad-css-practices/)) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/section/css_bad_practices_requirement.png) from Pathwright)
Take a look at this example:
![image](https://user-images.githubusercontent.com/56762529/90803794-a914df80-e2ef-11ea-9be0-40267c665254.png)
Your HTML will be something like this: 
![image](https://user-images.githubusercontent.com/56762529/90803950-e7120380-e2ef-11ea-8221-5d5d3a13e033.png)
Apply the same logic above in **ALL** those repeated rules listed below:
![image](https://user-images.githubusercontent.com/56762529/91914434-6dcec500-ec8e-11ea-8a11-4d1584100f8d.png)



## Please make the required changes and resubmit for a new code review once you are ready💪

## As always, I wish you all the very best and see you both at the top🚀


👨🏻‍💻 **TSE: Kevin Alves**

  

📫 Have any question? Better call Kevin:

<a  href="mailto:kevinalves.js@gmail.com"> <img  alt="gmail"  src="https://img.shields.io/badge/gmail-%20- green?logo=gmail&style=social"></a> [![Twitter Follow](https://img.shields.io/twitter/follow/kevinnnmn?style=social)](https://twitter.com/intent/follow?screen_name=kevinnnmn) [![](https://img.shields.io/badge/Slack-Kevin%20Alves-green?logo=slack&style=social)](https://microverse-students.slack.com/team/UT86D3AP4)

<sub>*We're here to help you, to ensure that you're using the best practices and getting you ready for the job market. In real-world, you'll have a lot of changes requests for your real clients, it's good to get used to it.</sub>

2020-09-01 22:52 UTC, kevincappuccino commented on css/style.css
> +} */
- [ ] Remove the commented code 🗑

2020-09-01 22:52 UTC, kevincappuccino commented on css/style.css
> +  /* width: 100%; */
- [ ] Remove the commented code 🗑

2020-09-01 22:52 UTC, kevincappuccino commented on css/style.css
> +  /* border: 1px solid #000; */
- [ ] Remove the commented code 🗑

2020-09-01 23:18 UTC, kevincappuccino commented on css/style.css
> +  color: #fff;
`color: #fff ` This rule repeats a lot (18x) you can create a class for that! 💪

2020-09-02 00:58 UTC, voscarmv approved these changes
# Impressive work! 🖥️ 👀 ✨ 

- Good job applying the changes required by Kevin.

# Status: Project Approved ✨ 😎👍 💯 ✔️
### You may merge this branch and move forward ⛙🛣

### Questions or comments? Reach me on [Twitter](https://twitter.com/voscarmv) or [LinkedIn](https://linkedin.com/in/oscar-mier) 🧑‍💻🗨️🧑‍💻 
# Happy Hacking! 🧠 ⌨️ 🖱️ 🖥️

2020-09-02 01:14 UTC, merged